export const EMOJI_NAMES: Record<string, string> = {
	'😀': 'grinning face', '😃': 'smiley', '😄': 'smile', '😁': 'grin',
	'😆': 'laughing', '😅': 'sweat smile', '🤣': 'rofl', '😂': 'joy',
	'🙂': 'slightly smiling', '😉': 'wink', '😊': 'blush', '😇': 'innocent halo',
	'🥰': 'smiling hearts love', '😍': 'heart eyes', '🤩': 'star struck',
	'😎': 'sunglasses cool', '🤓': 'nerd', '🧐': 'monocle', '😏': 'smirk',
	'🤔': 'thinking', '🤫': 'shushing quiet', '😴': 'sleeping zzz',
	'🤯': 'exploding head mind blown', '😱': 'scream fear', '🥳': 'party celebrate',
	'😈': 'devil', '👻': 'ghost', '💀': 'skull dead', '🤖': 'robot bot',
	'👽': 'alien ufo', '😡': 'angry rage', '😤': 'huffing steam', '😭': 'crying sob',
	'😢': 'sad tear', '😳': 'flushed embarrassed', '🥺': 'pleading puppy',
	'😬': 'grimacing awkward', '🤮': 'vomiting sick', '🤧': 'sneezing',
	'🥶': 'cold freezing', '🥵': 'hot sweating', '😶': 'no mouth silent',
	'😐': 'neutral', '😑': 'expressionless', '🫠': 'melting',
	'🤑': 'money mouth rich', '🤗': 'hugging', '🤭': 'giggling hand over mouth',
	'🫡': 'salute', '🫣': 'peeking', '🫢': 'open eyes hand over mouth',
	'😮': 'open mouth surprised', '😯': 'hushed', '😲': 'astonished',
	'😵': 'dizzy face', '🥴': 'woozy drunk', '😷': 'mask medical',
	'🤒': 'thermometer sick', '🤕': 'bandage hurt', '🤐': 'zipper mouth secret',
	'😶‍🌫️': 'face in clouds', '🫥': 'dotted line invisible', '🤥': 'lying pinocchio',
	'👍': 'thumbs up like', '👎': 'thumbs down dislike', '👋': 'wave hello',
	'✋': 'raised hand stop', '👏': 'clap applause', '🤝': 'handshake deal',
	'✌️': 'peace victory', '🤞': 'crossed fingers luck', '💪': 'muscle strong',
	'✍️': 'writing hand', '🙏': 'pray please thanks', '🤌': 'pinched fingers italian',
	'🤏': 'pinching small', '🤙': 'call me hang loose', '🖖': 'vulcan spock',
	'🫶': 'heart hands', '🤟': 'love you gesture', '🤘': 'rock on horns',
	'👌': 'ok perfect', '🫰': 'hand with index finger and thumb crossed',
	'❤️': 'red heart love', '🧡': 'orange heart', '💛': 'yellow heart',
	'💚': 'green heart', '💙': 'blue heart', '💜': 'purple heart',
	'🖤': 'black heart', '🤍': 'white heart', '💔': 'broken heart',
	'❤️‍🔥': 'heart on fire', '❤️‍🩹': 'mending heart',
	'💯': 'hundred perfect score', '💥': 'collision boom bang', '💫': 'dizzy star',
	'💬': 'speech bubble comment', '💭': 'thought bubble think',
	'👤': 'person silhouette user', '👥': 'people group users',
	'👶': 'baby child', '👦': 'boy', '👧': 'girl', '👨': 'man', '👩': 'woman',
	'👴': 'old man elder', '👵': 'old woman elder',
	'🧒': 'child', '🧓': 'older person', '🧔': 'bearded person',
	'🧑‍💻': 'technologist programmer developer', '🧑‍🎓': 'student graduate',
	'🧑‍🏫': 'teacher professor', '🧑‍🔬': 'scientist researcher',
	'🧑‍🎨': 'artist painter', '🧑‍🚀': 'astronaut space', '🧑‍⚕️': 'doctor health',
	'🧑‍🍳': 'cook chef', '🧑‍🔧': 'mechanic', '🧑‍🏭': 'factory worker',
	'🧑‍💼': 'office worker', '🧑‍🚒': 'firefighter',
	'🐶': 'dog puppy', '🐱': 'cat kitten', '🐭': 'mouse rat', '🐹': 'hamster',
	'🐰': 'rabbit bunny', '🦊': 'fox', '🐻': 'bear', '🐼': 'panda',
	'🐨': 'koala', '🦁': 'lion king', '🐯': 'tiger', '🐮': 'cow',
	'🐷': 'pig', '🐸': 'frog', '🐵': 'monkey', '🐔': 'chicken',
	'🐧': 'penguin', '🐦': 'bird', '🦅': 'eagle', '🦉': 'owl wisdom',
	'🦋': 'butterfly', '🐛': 'bug insect', '🐝': 'bee honeybee', '🐞': 'ladybug',
	'🐢': 'turtle tortoise', '🐍': 'snake', '🦎': 'lizard', '🐙': 'octopus',
	'🦈': 'shark', '🐳': 'whale ocean', '🐬': 'dolphin', '🦄': 'unicorn magic',
	'🐲': 'dragon', '🐴': 'horse', '🐺': 'wolf', '🐗': 'boar',
	'🐻‍❄️': 'polar bear', '🦝': 'raccoon', '🦫': 'beaver', '🦦': 'otter',
	'🦥': 'sloth', '🦨': 'skunk', '🦘': 'kangaroo', '🦡': 'badger',
	'🐾': 'paw prints', '🦃': 'turkey', '🐓': 'rooster', '🦆': 'duck',
	'🦢': 'swan', '🦜': 'parrot', '🪶': 'feather', '🦩': 'flamingo',
	'🦚': 'peacock', '🐊': 'crocodile', '🐉': 'dragon face',
	'🦕': 'sauropod dinosaur', '🦖': 'trex dinosaur', '🐋': 'whale',
	'🦭': 'seal', '🐟': 'fish', '🐠': 'tropical fish', '🐡': 'blowfish',
	'🦐': 'shrimp', '🦞': 'lobster', '🦀': 'crab', '🦑': 'squid',
	'🐌': 'snail', '🦗': 'cricket', '🪲': 'beetle', '🪳': 'cockroach',
	'🕷️': 'spider', '🕸️': 'spider web', '🦟': 'mosquito', '🪰': 'fly',
	'🪱': 'worm', '🦠': 'microbe bacteria virus',
	'🌸': 'cherry blossom flower', '🌹': 'rose flower', '🌻': 'sunflower',
	'🌺': 'hibiscus flower', '🌷': 'tulip flower', '🌱': 'seedling sprout grow',
	'🌲': 'evergreen tree pine', '🌳': 'deciduous tree', '🍀': 'four leaf clover luck',
	'🍁': 'maple leaf autumn', '🍂': 'fallen leaf autumn', '🌿': 'herb leaf green',
	'🌵': 'cactus desert', '🍄': 'mushroom', '🪴': 'potted plant',
	'🌾': 'rice sheaf', '🪻': 'hyacinth', '🪷': 'lotus',
	'🍎': 'apple red fruit', '🍊': 'orange tangerine fruit', '🍋': 'lemon citrus',
	'🍇': 'grapes fruit', '🍓': 'strawberry fruit', '🍒': 'cherry fruit',
	'🍑': 'peach fruit', '🍌': 'banana fruit', '🍉': 'watermelon fruit',
	'🍕': 'pizza food', '🍔': 'hamburger burger food', '🍟': 'fries food',
	'🌮': 'taco food', '🍰': 'cake dessert birthday', '🍩': 'donut doughnut dessert',
	'🍪': 'cookie dessert', '🍫': 'chocolate bar candy',
	'🥑': 'avocado', '🥕': 'carrot', '🌽': 'corn', '🥦': 'broccoli',
	'🧄': 'garlic', '🧅': 'onion', '🥒': 'cucumber', '🫑': 'bell pepper',
	'🥐': 'croissant', '🥖': 'baguette bread', '🥨': 'pretzel',
	'🧀': 'cheese', '🥩': 'meat steak', '🍗': 'poultry chicken leg',
	'🌭': 'hot dog', '🥪': 'sandwich', '🍣': 'sushi', '🍜': 'ramen noodles',
	'🍝': 'pasta spaghetti', '🍛': 'curry rice', '🍲': 'pot stew',
	'🥗': 'salad green', '🍿': 'popcorn', '🧁': 'cupcake',
	'🍦': 'ice cream', '🍧': 'shaved ice', '🍨': 'ice cream sundae',
	'🎂': 'birthday cake', '🍮': 'custard pudding', '🍯': 'honey pot',
	'☕': 'coffee hot beverage', '🍵': 'tea green', '🍺': 'beer mug drink',
	'🍷': 'wine glass drink', '🥤': 'cup straw beverage drink',
	'🍶': 'sake', '🍾': 'champagne bottle', '🥂': 'clinking glasses cheers',
	'🥃': 'tumbler whiskey', '🫗': 'pouring liquid', '🧋': 'bubble tea boba',
	'🧃': 'juice box', '🧊': 'ice cube',
	'🏠': 'house home', '🏡': 'house garden home', '🏢': 'office building',
	'🏫': 'school building', '🏥': 'hospital building', '🏰': 'castle',
	'🗼': 'tower', '🗽': 'statue liberty', '⛪': 'church religion',
	'🕌': 'mosque religion', '⛩️': 'shinto shrine torii',
	'🌍': 'earth globe world europe africa', '🌎': 'earth globe world americas',
	'🌏': 'earth globe world asia', '🗺️': 'world map',
	'🏔️': 'mountain snow', '⛰️': 'mountain', '🌋': 'volcano',
	'🏝️': 'desert island', '🏖️': 'beach umbrella',
	'🚗': 'car automobile', '🚕': 'taxi cab', '🚌': 'bus',
	'🚀': 'rocket launch space', '✈️': 'airplane plane flight travel',
	'🚁': 'helicopter', '🚢': 'ship boat', '🚂': 'train locomotive',
	'🚲': 'bicycle bike', '⛵': 'sailboat', '🛸': 'flying saucer ufo',
	'🚃': 'railway car', '🚄': 'high speed train', '🚅': 'bullet train',
	'🚆': 'train', '🚇': 'metro subway', '🚈': 'light rail',
	'🚉': 'station', '🚊': 'tram', '🚝': 'monorail', '🚞': 'mountain railway',
	'🚋': 'tram car', '🚍': 'bus front', '🚎': 'trolleybus',
	'🚐': 'minibus', '🚑': 'ambulance', '🚒': 'fire engine',
	'🚓': 'police car', '🚔': 'police car oncoming', '🚖': 'taxi oncoming',
	'🚘': 'automobile oncoming', '🚙': 'suv sport utility',
	'🛻': 'pickup truck', '🚚': 'delivery truck', '🚛': 'articulated lorry',
	'🚜': 'tractor farm', '🛵': 'motor scooter', '🏍️': 'motorcycle racing',
	'🛺': 'auto rickshaw', '🚠': 'mountain cableway', '🚡': 'aerial tramway',
	'🛶': 'canoe kayak', '🚤': 'speedboat', '🛳️': 'passenger ship cruise',
	'⛴️': 'ferry', '🛥️': 'motor boat', '🛩️': 'small airplane',
	'🪂': 'parachute', '💺': 'seat', '🛰️': 'satellite',
	'⌚': 'watch time clock', '📱': 'phone mobile smartphone',
	'💻': 'laptop computer', '🖥️': 'desktop computer monitor',
	'⌨️': 'keyboard typing', '🖱️': 'mouse computer', '🖨️': 'printer',
	'💾': 'floppy disk save', '💿': 'cd optical disk', '📀': 'dvd disk',
	'🎮': 'gamepad controller game', '🕹️': 'joystick game',
	'🔋': 'battery power', '💡': 'light bulb idea', '🔦': 'flashlight torch',
	'📷': 'camera photo', '🎥': 'movie camera video film', '📹': 'video camera',
	'🔍': 'magnifying glass search left', '🔎': 'magnifying glass search right',
	'🔬': 'microscope science research', '🔭': 'telescope astronomy',
	'📡': 'satellite antenna', '🔑': 'key password', '🗝️': 'old key vintage',
	'🔒': 'lock locked security', '🔓': 'unlock unlocked open',
	'🔧': 'wrench tool fix', '🔨': 'hammer tool build', '⚙️': 'gear settings cog',
	'🧲': 'magnet', '⚡': 'lightning bolt zap electricity',
	'🧪': 'test tube experiment', '💊': 'pill medicine',
	'🩺': 'stethoscope medical doctor', '🧬': 'dna genetics',
	'🪛': 'screwdriver', '🪚': 'saw carpentry', '🪝': 'hook',
	'🧰': 'toolbox', '🪤': 'mousetrap',
	'⚗️': 'alembic chemistry', '🩻': 'x-ray', '🩸': 'drop of blood',
	'📝': 'memo note write pencil', '📋': 'clipboard', '📌': 'pushpin pin',
	'📎': 'paperclip attach', '✏️': 'pencil write edit',
	'🖊️': 'pen write', '🖋️': 'fountain pen write',
	'📐': 'triangular ruler', '📏': 'straight ruler',
	'📕': 'book red closed', '📗': 'book green', '📘': 'book blue',
	'📙': 'book orange', '📚': 'books stack library', '📖': 'open book read',
	'📓': 'notebook', '📒': 'ledger notebook', '📄': 'page document file',
	'📃': 'page curl document', '📑': 'bookmark tabs',
	'🗂️': 'card index dividers files', '📁': 'folder file', '📂': 'open folder file',
	'🗃️': 'card file box archive', '🗄️': 'file cabinet storage',
	'🗑️': 'wastebasket trash delete', '📊': 'bar chart graph statistics',
	'📈': 'chart increasing up trend', '📉': 'chart decreasing down trend',
	'📆': 'calendar date', '📅': 'calendar', '🗓️': 'calendar spiral date',
	'📬': 'mailbox mail', '📧': 'email e-mail', '📩': 'envelope arrow email incoming',
	'📤': 'outbox tray upload', '📥': 'inbox tray download',
	'📦': 'package box', '📪': 'mailbox closed', '📫': 'mailbox raised flag',
	'📮': 'postbox', '🏷️': 'label tag price',
	'⭐': 'star favorite', '🌟': 'glowing star shine', '✨': 'sparkles shine magic',
	'🔥': 'fire hot flame trending', '💧': 'water droplet',
	'🌊': 'wave ocean water', '☀️': 'sun sunny bright',
	'🌙': 'moon crescent night', '🌈': 'rainbow', '☁️': 'cloud',
	'❄️': 'snowflake cold winter', '🌪️': 'tornado', '🌤️': 'sun behind small cloud',
	'⛈️': 'thunder cloud rain', '🌧️': 'cloud rain', '🌨️': 'cloud snow',
	'☔': 'umbrella rain',
	'🎯': 'target bullseye goal', '🏆': 'trophy award winner cup',
	'🥇': 'gold medal first', '🥈': 'silver medal second',
	'🥉': 'bronze medal third', '🏅': 'medal sports',
	'🎪': 'circus tent', '🎨': 'palette art paint color',
	'🎭': 'performing arts theater masks', '🎬': 'clapper board movie film',
	'🎤': 'microphone karaoke', '🎧': 'headphones music audio',
	'🎵': 'music note', '🎶': 'music notes', '🎹': 'piano musical keyboard',
	'🎸': 'guitar music', '🎺': 'trumpet music', '🥁': 'drum music',
	'🎻': 'violin', '🪗': 'accordion', '🎷': 'saxophone',
	'🎲': 'dice game random', '♟️': 'chess pawn strategy',
	'🧩': 'puzzle piece jigsaw', '🎁': 'gift present wrapped',
	'🎀': 'ribbon bow', '🎈': 'balloon party',
	'🎉': 'party popper celebrate tada', '🎊': 'confetti ball celebrate',
	'🎗️': 'reminder ribbon awareness',
	'⚽': 'soccer football', '🏀': 'basketball', '🏈': 'american football',
	'⚾': 'baseball', '🎾': 'tennis', '🏐': 'volleyball',
	'🏉': 'rugby', '🎱': 'billiards pool', '🏓': 'table tennis ping pong',
	'🏸': 'badminton', '🥊': 'boxing glove', '🥋': 'martial arts',
	'🏋️': 'weight lifting', '🤸': 'cartwheeling gymnastics',
	'⛷️': 'skier', '🏂': 'snowboarder', '🏄': 'surfer', '🚣': 'rowing',
	'🏊': 'swimming', '🧗': 'climbing', '🚴': 'cycling bicyclist',
	'🧘': 'yoga meditation', '🎣': 'fishing', '🪁': 'kite',
	'✅': 'check mark done complete', '❌': 'cross mark error wrong',
	'⚠️': 'warning alert caution', '🚫': 'prohibited forbidden no',
	'❓': 'question mark', '❗': 'exclamation mark important',
	'‼️': 'double exclamation', '⁉️': 'exclamation question',
	'🔴': 'red circle dot', '🟠': 'orange circle dot', '🟡': 'yellow circle dot',
	'🟢': 'green circle dot', '🔵': 'blue circle dot', '🟣': 'purple circle dot',
	'⚫': 'black circle dot', '⚪': 'white circle dot',
	'🟤': 'brown circle dot',
	'🟥': 'red square', '🟧': 'orange square', '🟨': 'yellow square',
	'🟩': 'green square', '🟦': 'blue square', '🟪': 'purple square',
	'⬛': 'black large square', '⬜': 'white large square',
	'🟫': 'brown square',
	'⬆️': 'arrow up', '⬇️': 'arrow down', '⬅️': 'arrow left',
	'➡️': 'arrow right', '↩️': 'arrow return back',
	'🔄': 'arrows counterclockwise refresh', '🔀': 'shuffle twisted arrows',
	'🔁': 'repeat loop', '▶️': 'play button', '⏸️': 'pause button',
	'⏹️': 'stop button', '⏩': 'fast forward', '⏪': 'rewind',
	'🏳️': 'white flag surrender', '🏴': 'black flag',
	'🚩': 'triangular flag red', '🏁': 'checkered flag race finish',
	'♻️': 'recycling recycle', '🔗': 'link chain',
	'📢': 'loudspeaker announce', '🔔': 'bell notification',
	'🔕': 'bell slash no notification mute', '🛡️': 'shield protect security',
	'⚔️': 'crossed swords fight', '🏹': 'bow arrow archery',
	'💎': 'gem diamond jewel', '👑': 'crown king queen royal',
	'🎓': 'graduation cap education', '🧠': 'brain mind think intelligence',
	'👁️': 'eye see look vision', '👀': 'eyes see look',
	'🫀': 'anatomical heart organ', '🦷': 'tooth dental', '🦴': 'bone skeleton',
	'💍': 'ring wedding diamond', '👓': 'glasses eyeglasses',
	'🕶️': 'sunglasses dark', '🧳': 'luggage suitcase travel',
	'🎒': 'backpack school bag', '🛒': 'shopping cart',
	'⏰': 'alarm clock time', '⏳': 'hourglass time sand',
	'🧭': 'compass navigation direction',
	'📍': 'pin location map', '🔐': 'locked key secure',
	'🕯️': 'candle light', '💰': 'money bag', '💵': 'dollar banknote',
	'💳': 'credit card', '🧾': 'receipt', '💸': 'money with wings flying',
	'🪙': 'coin', '🎰': 'slot machine jackpot',
	'🪄': 'magic wand', '🔮': 'crystal ball fortune', '🧿': 'nazar amulet evil eye',
	'🪬': 'hamsa', '♾️': 'infinity', '🎴': 'flower playing cards',
	'🀄': 'mahjong', '🃏': 'joker card',
	'🛁': 'bathtub', '🚿': 'shower', '🪥': 'toothbrush', '🧴': 'lotion bottle',
	'🧷': 'safety pin', '🧹': 'broom', '🪣': 'bucket', '🧺': 'basket',
	'🧻': 'toilet paper roll', '🚽': 'toilet', '🪞': 'mirror',
	'🪟': 'window', '🛏️': 'bed', '🛋️': 'couch lamp', '🪑': 'chair',
	'🚪': 'door', '🧯': 'fire extinguisher',
	'💈': 'barber pole', '🏺': 'amphora vase',
	// Additional smileys and faces
	'🥲': 'smiling tear happy sad', '🫤': 'face diagonal mouth', '🫨': 'shaking face',
	'🫩': 'face with bags under eyes tired', '😋': 'yum delicious savoring',
	'😜': 'winking tongue playful', '🤪': 'zany crazy', '😝': 'squinting tongue',
	'😛': 'tongue out', '🥸': 'disguised face',
	'😒': 'unamused', '😞': 'disappointed sad', '😔': 'pensive sad',
	'😟': 'worried', '😕': 'confused', '🙁': 'slightly frowning',
	'😣': 'persevering', '😖': 'confounded', '😫': 'tired weary',
	'😩': 'weary exhausted', '🥱': 'yawning bored',
	'🤬': 'cursing swearing angry', '😠': 'angry',
	'🫧': 'bubbles soap', '💨': 'dashing away wind fast',
	'💦': 'sweat droplets splashing',
	'💤': 'zzz sleeping', '🕳️': 'hole',
	'💣': 'bomb explosive', '🗨️': 'left speech bubble',
	'🗯️': 'right anger bubble', '💢': 'anger symbol',
	// More hand gestures
	'🖐️': 'hand with fingers splayed', '🤚': 'raised back of hand',
	'👊': 'fist bump punch', '✊': 'raised fist power',
	'🫳': 'palm down hand', '🫴': 'palm up hand',
	'🫲': 'leftwards hand', '🫱': 'rightwards hand',
	'👈': 'pointing left', '👉': 'pointing right',
	'👆': 'pointing up', '👇': 'pointing down',
	'☝️': 'index pointing up', '🖕': 'middle finger',
	'🫵': 'index pointing at viewer', '🤲': 'palms up together',
	'🙌': 'raising hands hooray',
	'🤳': 'selfie',
	// Body and people
	'🦶': 'foot', '🦵': 'leg', '🫁': 'lungs breathing',
	'🦻': 'ear hearing', '👂': 'ear', '👃': 'nose smell',
	'🦿': 'mechanical leg prosthetic', '🦾': 'mechanical arm prosthetic',
	'💅': 'nail polish', '🤷': 'shrug', '🤦': 'facepalm',
	'🙆': 'ok gesture person', '🙅': 'no good person',
	'💇': 'haircut', '💆': 'massage', '🧖': 'person in steamy room sauna',
	'🛀': 'person taking bath', '🧑‍🦯': 'person with white cane blind',
	'🧑‍🦼': 'person in motorized wheelchair', '🧑‍🦽': 'person in manual wheelchair',
	'🧙': 'mage wizard', '🧚': 'fairy', '🧛': 'vampire', '🧜': 'merperson',
	'🧝': 'elf', '🧞': 'genie', '🧟': 'zombie',
	'🧑‍🤝‍🧑': 'people holding hands', '👫': 'man woman holding hands couple',
	'👬': 'men holding hands', '👭': 'women holding hands',
	'💏': 'kiss couple', '💑': 'couple with heart love',
	'👪': 'family', '🧑‍🧑‍🧒': 'family parents child',
	'🫂': 'people hugging embrace',
	// More animals
	'🐀': 'rat', '🐁': 'mouse small', '🐂': 'ox', '🐃': 'water buffalo',
	'🐄': 'cow dairy', '🐅': 'tiger full', '🐆': 'leopard',
	'🐇': 'rabbit full', '🐈': 'cat full', '🐈‍⬛': 'black cat',
	'🐩': 'poodle dog', '🦮': 'guide dog', '🐕‍🦺': 'service dog',
	'🐕': 'dog full', '🐎': 'horse racing', '🫎': 'moose elk',
	'🫏': 'donkey', '🦌': 'deer', '🦬': 'bison buffalo',
	'🦣': 'mammoth woolly', '🦏': 'rhinoceros', '🦛': 'hippopotamus hippo',
	'🐪': 'camel one hump', '🐫': 'two hump camel',
	'🦒': 'giraffe', '🐘': 'elephant', '🐏': 'ram sheep',
	'🐑': 'ewe sheep', '🐐': 'goat', '🦙': 'llama alpaca',
	'🦔': 'hedgehog', '🐿️': 'chipmunk',
	'🐦‍⬛': 'black bird crow raven', '🦤': 'dodo extinct',
	'🪿': 'goose', '🦧': 'orangutan', '🐒': 'monkey full',
	'🦍': 'gorilla ape', '🐖': 'pig full',
	'🪸': 'coral reef', '🪼': 'jellyfish',
	'🐚': 'shell seashell', '🐜': 'ant',
	'🦂': 'scorpion',
	// More plants and nature
	'🌼': 'blossom flower', '💐': 'bouquet flowers',
	'🌰': 'chestnut nut', '🫘': 'beans',
	'🪹': 'empty nest', '🪺': 'nest with eggs',
	'🌑': 'new moon dark', '🌒': 'waxing crescent moon',
	'🌓': 'first quarter moon', '🌔': 'waxing gibbous moon',
	'🌕': 'full moon', '🌖': 'waning gibbous moon',
	'🌗': 'last quarter moon', '🌘': 'waning crescent moon',
	'🌚': 'new moon face', '🌛': 'first quarter moon face',
	'🌜': 'last quarter moon face', '🌝': 'full moon face',
	'🌞': 'sun with face', '🪐': 'ringed planet saturn',
	'🌠': 'shooting star', '🌌': 'milky way galaxy night sky',
	'🌫️': 'fog', '🌬️': 'wind face blowing',
	'🌀': 'cyclone hurricane typhoon spiral', '🌁': 'foggy',
	// More food and drink
	'🍠': 'sweet potato roasted', '🥔': 'potato', '🥚': 'egg',
	'🍳': 'cooking egg fried', '🥓': 'bacon', '🥞': 'pancakes',
	'🧇': 'waffle', '🥯': 'bagel', '🫓': 'flatbread',
	'🫔': 'tamale', '🥙': 'stuffed flatbread pita', '🧆': 'falafel',
	'🥘': 'shallow pan paella', '🫕': 'fondue', '🥫': 'canned food',
	'🍱': 'bento box japanese lunch', '🍘': 'rice cracker',
	'🍙': 'rice ball onigiri', '🍚': 'cooked rice',
	'🍢': 'oden skewer', '🍡': 'dango', '🥟': 'dumpling',
	'🥠': 'fortune cookie', '🥡': 'takeout box',
	'🥧': 'pie', '🍬': 'candy sweet',
	'🍭': 'lollipop candy',
	'🫖': 'teapot', '🍼': 'baby bottle milk', '🥛': 'glass of milk',
	'🫙': 'jar container', '🍽️': 'plate cutlery fork knife',
	'🥢': 'chopsticks', '🥄': 'spoon', '🔪': 'kitchen knife hocho',
	// More buildings and places
	'🏗️': 'construction building crane', '🏘️': 'houses neighborhood',
	'🏚️': 'derelict house abandoned', '🏛️': 'classical building columns',
	'🏙️': 'cityscape skyline', '🌃': 'night with stars city',
	'🌆': 'cityscape at dusk sunset', '🌇': 'sunset city',
	'🌅': 'sunrise morning', '🌄': 'sunrise over mountains',
	'🏜️': 'desert', '🏞️': 'national park nature',
	'🎠': 'carousel horse merry go round', '🎡': 'ferris wheel',
	'🎢': 'roller coaster', '🏟️': 'stadium',
	'🕍': 'synagogue jewish', '🛕': 'hindu temple',
	'🕋': 'kaaba mecca', '⛲': 'fountain water',
	'⛺': 'tent camping', '🏕️': 'camping tent nature',
	// More objects
	'🪔': 'diya lamp oil', '📺': 'television tv monitor',
	'📻': 'radio', '📠': 'fax machine',
	'🔊': 'speaker loud volume high', '🔉': 'speaker medium volume',
	'🔈': 'speaker low volume', '🔇': 'muted speaker volume off',
	'📣': 'megaphone cheering', '🎙️': 'studio microphone podcast',
	'🎚️': 'level slider', '🎛️': 'control knobs',
	'🧮': 'abacus math calculate', '🖩': 'calculator',
	'📸': 'camera flash photo', '📽️': 'film projector',
	'🎞️': 'film frames', '📼': 'videocassette vhs tape',
	'🔌': 'electric plug power',
	'🪫': 'low battery', '💶': 'euro banknote', '💷': 'pound banknote',
	'💴': 'yen banknote', '🪪': 'identification card id',
	'🧫': 'petri dish biology',
	'🛗': 'elevator lift', '🪜': 'ladder steps',
	'⚖️': 'balance scale justice', '⛓️': 'chains linked',
	'⚓': 'anchor nautical ship',
	'🗿': 'moai easter island statue',
	// Zodiac and symbols
	'♈': 'aries zodiac', '♉': 'taurus zodiac', '♊': 'gemini zodiac',
	'♋': 'cancer zodiac', '♌': 'leo zodiac', '♍': 'virgo zodiac',
	'♎': 'libra zodiac', '♏': 'scorpio zodiac', '♐': 'sagittarius zodiac',
	'♑': 'capricorn zodiac', '♒': 'aquarius zodiac', '♓': 'pisces zodiac',
	'⛎': 'ophiuchus zodiac',
	// Country flags
	'🇺🇸': 'flag usa america united states', '🇬🇧': 'flag uk britain england',
	'🇫🇷': 'flag france french', '🇩🇪': 'flag germany german',
	'🇮🇹': 'flag italy italian', '🇪🇸': 'flag spain spanish',
	'🇷🇺': 'flag russia russian', '🇨🇳': 'flag china chinese',
	'🇯🇵': 'flag japan japanese', '🇰🇷': 'flag korea south korean',
	'🇧🇷': 'flag brazil brazilian', '🇮🇳': 'flag india indian',
	'🇨🇦': 'flag canada canadian', '🇦🇺': 'flag australia australian',
	'🇲🇽': 'flag mexico mexican', '🇦🇷': 'flag argentina',
	'🇹🇷': 'flag turkey turkish', '🇸🇦': 'flag saudi arabia',
	'🇳🇱': 'flag netherlands dutch', '🇸🇪': 'flag sweden swedish',
	'🇳🇴': 'flag norway norwegian', '🇩🇰': 'flag denmark danish',
	'🇫🇮': 'flag finland finnish', '🇵🇱': 'flag poland polish',
	'🇺🇦': 'flag ukraine ukrainian', '🇨🇭': 'flag switzerland swiss',
	'🇦🇹': 'flag austria', '🇧🇪': 'flag belgium',
	'🇵🇹': 'flag portugal portuguese', '🇬🇷': 'flag greece greek',
	'🇮🇪': 'flag ireland irish', '🇮🇱': 'flag israel',
	'🇪🇬': 'flag egypt', '🇿🇦': 'flag south africa',
	'🇹🇭': 'flag thailand thai', '🇻🇳': 'flag vietnam vietnamese',
	'🇮🇩': 'flag indonesia', '🇵🇭': 'flag philippines',
	'🇳🇿': 'flag new zealand', '🇸🇬': 'flag singapore',
	'🇲🇾': 'flag malaysia', '🇨🇴': 'flag colombia',
	'🇨🇱': 'flag chile', '🇵🇪': 'flag peru',
	'🇰🇿': 'flag kazakhstan', '🇬🇪': 'flag georgia',
	'🏴‍☠️': 'pirate flag jolly roger',
	'🏳️‍🌈': 'rainbow flag pride lgbtq', '🏳️‍⚧️': 'transgender flag',
	// More misc symbols
	'☮️': 'peace symbol', '✝️': 'latin cross christian',
	'☪️': 'star and crescent islam', '🕉️': 'om hindu buddhist',
	'☯️': 'yin yang balance', '✡️': 'star of david jewish',
	'🔯': 'six pointed star', '☸️': 'wheel of dharma buddhism',
	'🛐': 'place of worship', '⚛️': 'atom symbol science',
	'☢️': 'radioactive nuclear', '☣️': 'biohazard',
	'🆔': 'id identity', '⚕️': 'medical symbol caduceus',
	'Ⓜ️': 'circled m metro', '🅰️': 'a button blood type',
	'🅱️': 'b button blood type', '🆎': 'ab button blood type',
	'🅾️': 'o button blood type', '🆘': 'sos emergency help',
	'🆚': 'vs versus', '🆗': 'ok button',
	'🆕': 'new button', '🆓': 'free button',
	'🈁': 'japanese here', '🈂️': 'japanese service charge',
	'🔰': 'japanese symbol beginner', '♀️': 'female sign woman',
	'♂️': 'male sign man', '⚧️': 'transgender symbol',
	'✖️': 'multiply cross', '➕': 'plus add', '➖': 'minus subtract',
	'➗': 'divide', '🟰': 'equals sign',
	'#️⃣': 'hash number sign', '*️⃣': 'asterisk keycap',
	'0️⃣': 'zero keycap', '1️⃣': 'one keycap', '2️⃣': 'two keycap',
	'3️⃣': 'three keycap', '4️⃣': 'four keycap', '5️⃣': 'five keycap',
	'6️⃣': 'six keycap', '7️⃣': 'seven keycap', '8️⃣': 'eight keycap',
	'9️⃣': 'nine keycap', '🔟': 'ten keycap',
	'🅿️': 'parking button', '🈳': 'japanese vacancy',
	'🈴': 'japanese passing grade', '🈵': 'japanese no vacancy',
	'🈹': 'japanese discount', '🈲': 'japanese prohibited',
	'🉐': 'japanese bargain', '🈶': 'japanese not free of charge',
	'🈚': 'japanese free of charge',
	'🔝': 'top arrow', '🔙': 'back arrow', '🔛': 'on arrow',
	'🔜': 'soon arrow', '🔚': 'end arrow',
	'↕️': 'up down arrow', '↔️': 'left right arrow',
	'↗️': 'northeast arrow', '↘️': 'southeast arrow',
	'↙️': 'southwest arrow', '↖️': 'northwest arrow',
	'⤴️': 'right arrow curving up', '⤵️': 'right arrow curving down',
	'🔂': 'repeat single loop one', '🔃': 'clockwise arrows',
	'◀️': 'reverse button rewind', '⏭️': 'next track',
	'⏮️': 'previous track', '⏯️': 'play pause toggle',
	'🔅': 'dim button brightness low', '🔆': 'bright button brightness high',
	'📶': 'signal bars antenna', '📳': 'vibration mode',
	'📴': 'mobile phone off', '🔘': 'radio button',
	'🔲': 'black square button', '🔳': 'white square button',
	'🔺': 'red triangle up', '🔻': 'red triangle down',
	'🔸': 'small orange diamond', '🔹': 'small blue diamond',
	'🔶': 'large orange diamond', '🔷': 'large blue diamond',
	'◻️': 'white medium square', '◼️': 'black medium square',
	'◽': 'white medium small square', '◾': 'black medium small square',
	'▪️': 'black small square', '▫️': 'white small square',
	'💠': 'diamond shape with dot inside blue',
	'©️': 'copyright', '®️': 'registered trademark', '™️': 'trademark',
};
